[package]
edition = "2024"
name = "makemkv"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process", "sync", "time"] }
zerocopy = { workspace = true }
