[workspace]
members = ["makemkv", "rippa"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.102"
askama = "0.16.0"
axum = { version = "0.8.9", features = ["macros"] }
chrono = "0.4.45"
flate2 = "1.1.9"
log = "0.4.32"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["io-util"] }
zerocopy = { version = "0.8.52", features = ["derive"] }

[workspace.lints.rust]
unsafe_code = "forbid"
