use crate::error::RippaError;
use zerocopy::{FromBytes, KnownLayout, byteorder::little_endian::U16};

#[derive(Copy, Clone, Debug)]
#[repr(u8)]
pub enum MakeMkvCommand {
    Nop = 0,
    Return = 1,
    ClientDone = 2,
    CallSignalExit = 3,
    CallOnIdle = 4,
    // CallCancelAllJobs = 4,
    CallSetOutputFolder = 16,
    CallUpdateAvailableDrives = 17,
    CallOpenFile = 18,
    CallOpenCdDisk = 19,
    CallOpenTitleCollection = 20,
    CallCloseDisk = 21,
    CallEjectDisk = 22,
    CallSaveAllSelectedTitlesToMkv = 23,
    CallGetUiItemState = 24,
    CallSetUiItemState = 25,
    CallGetUiItemInfo = 26,
    CallGetSettingInt = 27,
    CallGetSettingString = 28,
    CallSetSettingInt = 29,
    CallSetSettingString = 30,
    CallSaveSettings = 31,
    CallAppGetString = 32,
    CallBackupDisc = 33,
    CallGetInterfaceLanguageData = 34,
    CallSetUiItemInfo = 35,
    CallSetProfile = 36,
    CallInitMMBD = 37,
    CallOpenMMBD = 38,
    CallDiscInfoMMBD = 39,
    CallDecryptUnitMMBD = 40,
    CallSetExternAppFlags = 41,
    CallManageState = 42,
    CallAppSetString = 43,
    BackEnterJobMode = 192,
    BackLeaveJobMode = 193,
    BackUpdateDrive = 194,
    BackUpdateCurrentBar = 195,
    BackUpdateTotalBar = 196,
    BackUpdateLayout = 197,
    BackSetTotalName = 198,
    BackUpdateCurrentInfo = 199,
    BackReportUiMessage = 200,
    BackExit = 201,
    BackSetTitleCollInfo = 202,
    BackSetTitleInfo = 203,
    BackSetTrackInfo = 204,
    BackSetChapterInfo = 205,
    BackReportUiDialog = 206,
    BackFatalCommError = 224,
    BackOutOfMem = 225,
    Unknown = 239,
}

impl TryFrom<u8> for MakeMkvCommand {
    type Error = RippaError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Nop),
            1 => Ok(Self::Return),
            2 => Ok(Self::ClientDone),
            3 => Ok(Self::CallSignalExit),
            4 => Ok(Self::CallOnIdle),
            16 => Ok(Self::CallSetOutputFolder),
            17 => Ok(Self::CallUpdateAvailableDrives),
            18 => Ok(Self::CallOpenFile),
            19 => Ok(Self::CallOpenCdDisk),
            20 => Ok(Self::CallOpenTitleCollection),
            21 => Ok(Self::CallCloseDisk),
            22 => Ok(Self::CallEjectDisk),
            23 => Ok(Self::CallSaveAllSelectedTitlesToMkv),
            24 => Ok(Self::CallGetUiItemState),
            25 => Ok(Self::CallSetUiItemState),
            26 => Ok(Self::CallGetUiItemInfo),
            27 => Ok(Self::CallGetSettingInt),
            28 => Ok(Self::CallGetSettingString),
            29 => Ok(Self::CallSetSettingInt),
            30 => Ok(Self::CallSetSettingString),
            31 => Ok(Self::CallSaveSettings),
            32 => Ok(Self::CallAppGetString),
            33 => Ok(Self::CallBackupDisc),
            34 => Ok(Self::CallGetInterfaceLanguageData),
            35 => Ok(Self::CallSetUiItemInfo),
            36 => Ok(Self::CallSetProfile),
            37 => Ok(Self::CallInitMMBD),
            38 => Ok(Self::CallOpenMMBD),
            39 => Ok(Self::CallDiscInfoMMBD),
            40 => Ok(Self::CallDecryptUnitMMBD),
            41 => Ok(Self::CallSetExternAppFlags),
            42 => Ok(Self::CallManageState),
            43 => Ok(Self::CallAppSetString),
            192 => Ok(Self::BackEnterJobMode),
            193 => Ok(Self::BackLeaveJobMode),
            194 => Ok(Self::BackUpdateDrive),
            195 => Ok(Self::BackUpdateCurrentBar),
            196 => Ok(Self::BackUpdateTotalBar),
            197 => Ok(Self::BackUpdateLayout),
            198 => Ok(Self::BackSetTotalName),
            199 => Ok(Self::BackUpdateCurrentInfo),
            200 => Ok(Self::BackReportUiMessage),
            201 => Ok(Self::BackExit),
            202 => Ok(Self::BackSetTitleCollInfo),
            203 => Ok(Self::BackSetTitleInfo),
            204 => Ok(Self::BackSetTrackInfo),
            205 => Ok(Self::BackSetChapterInfo),
            206 => Ok(Self::BackReportUiDialog),
            224 => Ok(Self::BackFatalCommError),
            225 => Ok(Self::BackOutOfMem),
            239 => Ok(Self::Unknown),
            _ => Err(RippaError::InvalidMmkvCommand(format!(
                "{} is not valid",
                value
            ))),
        }
    }
}

#[derive(FromBytes, KnownLayout)]
#[repr(C)]
pub struct MakeMkvHeader {
    pub data_size: U16,
    pub arg_len: u8,
    pub cmd: u8,
}
