[package]
edition = "2024"
name = "rippa"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
askama = { workspace = true }
axum = { workspace = true }
flexi_logger = "0.31.8"
log = { workspace = true }
makemkv = { path = "../makemkv" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
